// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyServer(arg1, arg2) {
  return window['go']['main']['App']['ApplyServer'](arg1, arg2);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function SetFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetFavorite'](arg1, arg2);
}
