// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyServer(arg1:string,arg2:string):Promise<void>;

export function GetAccounts():Promise<Array<string>>;

export function GetFavorites():Promise<Array<string>>;

export function GetServers():Promise<Array<main.ServerInfo>>;

export function SetFavorite(arg1:number,arg2:string):Promise<void>;
